-- SQL DDL + RLS untuk implementasi PRD Landing Page CRM Delita Dove
-- Jalankan file ini di Supabase SQL Editor sebelum memakai integrasi React.

create extension if not exists pgcrypto;

-- PRODUCTS: paket/layanan yang tampil di admin dan landing page publik.
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  code text not null unique,
  title text not null,
  category text not null,
  brand text default 'Delita Dove',
  price numeric(12, 2) not null default 0,
  stock integer not null default 0,
  image_url text,
  created_at timestamptz not null default now()
);

-- CUSTOMERS: data customer/prospek untuk halaman admin.
create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  customer_id text not null unique,
  customer_name text not null,
  email text,
  phone text,
  address text,
  city text,
  loyalty text not null default 'Bronze',
  status text not null default 'Active',
  join_date date default current_date,
  rating numeric(2, 1) default 0,
  admin_notes text,
  complaints jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

-- CAMPAIGNS: social proof / portfolio ringkas untuk landing page.
create table if not exists public.campaigns (
  id bigint generated by default as identity primary key,
  campaign_id text not null unique,
  name text not null,
  type text not null,
  start_date date,
  end_date date,
  participants_count integer not null default 0,
  image_url text,
  description text,
  created_at timestamptz not null default now()
);

-- ORDERS: booking/lead paket dari landing page.
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_id text not null unique,
  product_id bigint references public.products(id) on delete set null,
  product_code text,
  customer_name text not null,
  customer_email text,
  customer_phone text,
  package_name text not null,
  event_date date,
  guest_count integer,
  location text,
  total_price numeric(12, 2) not null default 0,
  notes text,
  promo_code text,
  status text not null default 'Pending',
  created_at timestamptz not null default now()
);

-- MESSAGES: inquiry/konsultasi umum dari landing page.
create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  message_type text not null,
  name text,
  email text,
  phone text not null,
  event_date date,
  location text,
  guest_count integer,
  message text not null,
  notes text,
  promo_code text,
  created_at timestamptz not null default now()
);

create index if not exists products_created_at_idx on public.products (created_at desc);
create index if not exists customers_created_at_idx on public.customers (created_at desc);
create index if not exists campaigns_created_at_idx on public.campaigns (created_at desc);
create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists messages_created_at_idx on public.messages (created_at desc);

alter table public.products enable row level security;
alter table public.customers enable row level security;
alter table public.campaigns enable row level security;
alter table public.orders enable row level security;
alter table public.messages enable row level security;

-- Drop policy bila pernah dibuat, supaya script aman dijalankan ulang.
drop policy if exists "products_select_public" on public.products;
drop policy if exists "products_admin_all" on public.products;
drop policy if exists "customers_admin_all" on public.customers;
drop policy if exists "campaigns_select_public" on public.campaigns;
drop policy if exists "campaigns_admin_all" on public.campaigns;
drop policy if exists "orders_insert_public" on public.orders;
drop policy if exists "orders_select_authenticated" on public.orders;
drop policy if exists "orders_admin_update_delete" on public.orders;
drop policy if exists "messages_insert_public" on public.messages;
drop policy if exists "messages_select_authenticated" on public.messages;

create policy "products_select_public"
on public.products for select
to anon, authenticated
using (true);

create policy "products_admin_all"
on public.products for all
to authenticated
using (true)
with check (true);

create policy "customers_admin_all"
on public.customers for all
to authenticated
using (true)
with check (true);

create policy "campaigns_select_public"
on public.campaigns for select
to anon, authenticated
using (true);

create policy "campaigns_admin_all"
on public.campaigns for all
to authenticated
using (true)
with check (true);

create policy "orders_insert_public"
on public.orders for insert
to anon, authenticated
with check (
  customer_name is not null
  and package_name is not null
);

create policy "orders_select_authenticated"
on public.orders for select
to authenticated
using (true);

create policy "orders_admin_update_delete"
on public.orders for update
to authenticated
using (true)
with check (true);

create policy "messages_insert_public"
on public.messages for insert
to anon, authenticated
with check (
  phone is not null
  and char_length(phone) >= 6
  and message is not null
);

create policy "messages_select_authenticated"
on public.messages for select
to authenticated
using (true);
